Logical operators:
(x and y) → both x and y must be True
(x or y) → either x or y must be True
(not x) → x must be false

In [1]:
# and ,or ,not
x, y = True, False
(x or y) == True # True
(x and y) == False # True
(not y) == True # True


True

Ends loop prematurely

In [2]:
#break
while(True):
     break # no infinite loop
print("hello world")


hello world


Finishes current loop iteration

In [ ]:
#continue
while(True):
    continue
    print("43") # dead code


Defines a new class → a real-world concept
(object oriented programming)
Defines a new function or class method. For latter,
first parameter (“self”) points to the class object.
When calling class method, first parameter is implicit.

In [ ]:
#class and def
class Beer:
    def __init__(self):
self.content = 1.0
 def drink(self):
self.content = 0.0
becks = Beer() # constructor - create class
becks.drink() # beer empty: b.content == 0



Conditional program execution: program starts with
“if” branch, tries the “elif” branches, and finishes with
“else” branch (until one branch evaluates to True).

In [ ]:
#if, elif, else
x = int(input("your value: "))
if x > 3: print("Big")
elif x == 3: print("Medium")
else: print("Small")

In [ ]:
#for, while 

# For loop declaration
for i in [0,1,2]:
    print(i)
# While loop - same semantics
j = 0
while j < 3:
    print(j)
 j = j + 1

Checks whether element is in sequence 

In [ ]:
#in
42 in [2, 39, 42] # True


Checks whether both elements point to the same
object


In [ ]:
#is
y = x = 3
x is y # True
[3] is [3] # False

Empty value constant 

In [ ]:
#None
def f():
    x = 2
f() is None # True

Function with no name (anonymous function) 

In [ ]:
#Lambda
(lambda x: x + 3)(3) # returns 6

Terminates execution of the function and passes the
flow of execution to the caller. An optional value after
the return keyword specifies the function result.

In [ ]:
#Return
def incrementor(x):
    return x + 1
incrementor(4) # returns 5


The Boolean data type is a truth value, either
True or False.
The Boolean operators ordered by priority:
not x → “if x is False, then x, else y”
x and y → “if x is False, then x, else y”
x or y → “if x is False, then y, else x”
These comparison operators evaluate to True:
1 < 2 and 0 <= 1 and 3 > 2 and 2 >=2 and
1 == 1 and 1 != 0 # True

In [ ]:
## 1. Boolean Operations
x, y = True, False
print(x and not y) # True
print(not x and y or x) # True

## 2. If condition evaluates to False
if None or 0 or 0.0 or '' or [] or {} or set():
 # None, 0, 0.0, empty strings, or empty
 # container types are evaluated to False
    print("Dead code") # Not reached

An integer is a positive or negative number
without floating point (e.g. 3). A float is a
positive or negative number with floating point
precision (e.g. 3.14159265359).
The ‘//’ operator performs integer division.
The result is an integer value that is rounded
towards the smaller integer number
(e.g. 3 // 2 == 1).

In [ ]:
#integer ,float
## 3. Arithmetic Operations
x, y = 3, 2
print(x + y) # = 5
print(x - y) # = 1
print(x * y) # = 6
print(x / y) # = 1.5
print(x // y) # = 1
print(x % y) # = 1s
print(-x) # = -3
print(abs(-x)) # = 3
print(int(3.9)) # = 3
print(float(3)) # = 3.0
print(x ** y) # = 9

Python Strings are sequences of characters.
The four main ways to create strings are the
following.
1. Single quotes
'Yes'
2. Double quotes
"Yes"
3. Triple quotes (multi-line)
"""Yes
We Can"""
4. String method
str(5) == '5' # True
5. Concatenation
"Ma" + "hatma" # 'Mahatma'
These are whitespace characters in strings.
● Newline \n
● Space \s
● Tab \t

In [ ]:
#string
## 4. Indexing and Slicing
s = "The youngest pope was 11 years old"
print(s[0]) # 'T'
print(s[1:3]) # 'he'
print(s[-3:-1]) # 'ol'
print(s[-3:]) # 'old'
x = s.split() # creates string array of words
print(x[-3] + " " + x[-1] + " " + x[2] + "s")
 # '11 old popes'
    
## 5. Most Important String Methods
y = " This is lazy\t\n "
print(y.strip()) # Remove Whitespace: 'This is lazy'
print("DrDre".lower()) # Lowercase: 'drdre'
print("attention".upper()) # Uppercase: 'ATTENTION'
print("smartphone".startswith("smart")) # True
print("smartphone".endswith("phone")) # True
print("another".find("other")) # Match index: 2
print("cheat".replace("ch", "m")) # 'meat'
print(','.join(["F", "B", "I"])) # 'F,B,I'
print(len("Rumpelstiltskin")) # String length: 15
print("ear" in "earth") # Contains: True


A container data type that stores a
sequence of elements. Unlike strings, lists
are mutable: modification possible.


In [32]:
#list
l = [1, 2, 2]
print(len(l)) # 3


3


Add elements to a list with (i) append, (ii)
insert, or (iii) list concatenation.
The append operation is very fast

In [33]:
[1, 2, 2].append(4) # [1, 2, 2, 4]
[1, 2, 4].insert(2,2) # [1, 2, 2, 4]
[1, 2, 2] + [4] # [1, 2, 2, 4]


[1, 2, 2, 4]

Removing an element can be slower. 

In [34]:
[1, 2, 2, 4].remove(1) # [2, 2, 4]

This reverses the order of list elements.

In [35]:
[1, 2, 3].reverse() # [3, 2, 1]

Sorts a list. The computational complexity
of sorting is O(n log n) for n list elements.

In [36]:
[2, 4, 2].sort() # [2, 2, 4]

Finds the first occurence of an element in
the list & returns its index. Can be slow as
the whole list is traversed.

In [37]:
[2, 2, 4].index(2) # index of element 4 is "0"
[2, 2, 4].index(2,1) # index of element 2 after pos 1 is "1"

1

Python lists can be used intuitively as stack
via the two list operations append() and
pop().

In [38]:
#stak
stack = [3]
stack.append(42) # [3, 42]
stack.pop() # 42 (stack: [3])
stack.pop() # 3 (stack: [])

3

A set is an unordered collection of
elements. Each can exist only once.


In [39]:
#set
basket = {'apple', 'eggs', 'banana', 'orange'}
same = set(['apple', 'eggs', 'banana', 'orange'])

The dictionary is a useful data structure for
storing (key, value) pairs.


In [40]:
#dictonary
calories = {'apple' : 52, 'banana' : 89, 'choco' : 546}

Read and write elements by specifying the
key within the brackets. Use the keys() and
values() functions to access all keys and
values of the dictionary.

In [41]:
print(calories['apple'] < calories['choco']) # True
calories['cappu'] = 74
print(calories['banana'] < calories['cappu']) # False
print('apple' in calories.keys()) # True
print(52 in calories.values()) # True

True
False
True
True


You can loop over the (key, value) pairs of
a dictionary with the items() method

In [43]:
for k, v in calories.items():
    print(k) if v > 500 else None # 'chocolate'

choco


Check with the ‘in’ keyword whether the
set, list, or dictionary contains an element.
Set containment is faster than list
containment

In [45]:
#Membership operator
basket = {'apple', 'eggs', 'banana', 'orange'}
print('eggs' in basket) # True
print('mushroom' in basket) # Fals

True
False


List comprehension is the concise Python
way to create lists. Use brackets plus an
expression, followed by a for clause. Close
with zero or more for or if clauses.
Set comprehension is similar to list
comprehension.

In [46]:
# List comprehension
l = [('Hi ' + x) for x in ['Alice', 'Bob', 'Pete']]
print(l) # ['Hi Alice', 'Hi Bob', 'Hi Pete']
l2 = [x * y for x in range(3) for y in range(3) if x>y]
print(l2) # [0, 0, 2]
# Set comprehension
squares = { x**2 for x in [0,2,4] if x < 4 } # {0, 4}

['Hi Alice', 'Hi Bob', 'Hi Pete']
[0, 0, 2]


A class encapsulates data and functionality - data as
attributes, and functionality as methods. It is a blueprint
to create concrete instances in the memory.

In [52]:
#class and instances
class Dog:
     """ Blueprint of a dog """
# class variable shared by all instances
species = ["canis lupus"]
def __init__(self, name, color):
    self.name = name
    self.state = "sleeping"
    self.color = color

In [60]:
def command(self, x):
    if x == self.name:
        self.bark(2)
    elif x == "sit":
        self.state = "sit"
    else:
            self.state = "wag tail"
def bark(self, freq):
    for i in range(freq):
        print("[" + self.name+ "]: Woof!")

You can create classes “on the fly” and use them as
logical units to store complex data types.

In [65]:
#creation
class Employee():
    pass
employee = Employee()
employee.salary = 122000
employee.firstname = "alice"
employee.lastname = "wonderland"
print(employee.firstname + " "
+ employee.lastname + " "
+ str(employee.salary) + "$")
# alice wonderland 122000$

alice wonderland 122000$


Executes the function on all elements of
the iterable

In [66]:
#map(func, iter) 
list(map(lambda x: x[0], ['red','green', 'blue']))

['r', 'g', 'b']

Executes the function on all k elements of
the k iterables

In [67]:
#map(func, i1, ...,ik)
list(map(lambda x, y: str(x) + ' ' +
y + 's' , [0, 2, 2], ['apple','orange', 'banana']))

['0 apples', '2 oranges', '2 bananas']

Concatenates iterable elements
separated by string

In [68]:
#string.join(iter)
' marries '.join(list(['Alice',
'Bob']))

'Alice marries Bob'

Filters out elements in iterable for which
function returns False (or 0)

In [69]:
#filter(func,iterable)
list(filter(lambda x: True if x>17
else False, [1, 15, 17, 18]))

[18]

Removes leading and trailing
whitespaces of string

In [70]:
#string.strip() 
print(" \n \t 42 \t ".strip()) 

42


Sorts iterable in ascending order

In [71]:
#sorted(iter) 
sorted([8, 3, 2, 42, 5]) 

[2, 3, 5, 8, 42]

Sorts according to the key function in
ascending order

In [72]:
#sorted(iter,key=key)
sorted([8, 3, 2, 42, 5], key=lambda
x: 0 if x==42 else x)

[42, 2, 3, 5, 8]

Groups the i-th elements of iterators i1, i2,
… together

In [74]:
#zip(i1, i2, ...) 
list(zip(['Alice', 'Anna'], ['Bob','Jon', 'Frank']))

[('Alice', 'Bob'), ('Anna', 'Jon')]

Equal to: 1) unpack the zipped list, 2) zip
the result

In [77]:
#unizp
list(zip(*[('Alice', 'Bob'),('Anna', 'Jon')]))

[('Alice', 'Anna'), ('Bob', 'Jon')]

Assigns a counter value to each element
of the iterable

In [78]:
#enumerate(inter)
list(enumerate(['Alice', 'Bob','Jon']))

[(0, 'Alice'), (1, 'Bob'), (2, 'Jon')]

In [80]:
#Get missingnumber in[1...100]
def get_missing_number(lst):
     return set(range(lst[len(lst)-1])[1:]) - set(l)
l = list(range(1,100))
l.remove(50)
print(get_missing_number(l)) # 50

{50}


In [81]:
#Check if listcontains integer x
l = [3, 3, 4, 5, 2, 111, 5]
print(111 in l) # True

True


In [ ]:
#Computethe intersection of two lists
def intersect(lst1, lst2):
     res, lst2_copy = [], lst2[:]
for el in lst1:
     if el in lst2_copy:
        res.append(el)
lst2_copy.remove(el)
return res

In [85]:
#Find maxand min in unsorted lis
l = [4, 3, 6, 3, 4, 888, 1, -11, 22, 3]
print(max(l)) # 888
print(min(l)) # -11

888
-11


In [87]:
#Check if two strings are anagrams
def is_anagram(s1, s2):
      return set(s1) == set(s2)
print(is_anagram("elvis", "lives")) # True

True


In [89]:
#Reverse string using recursion
def reverse(string):
    if len(string)<=1: return string
    return reverse(string[1:])+string[0]
print(reverse("hello")) # olleh

olleh


In [90]:
#Remove all duplicates from list
lst = list(range(10)) + list(range(10))
lst = list(set(lst))
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [93]:
#Find pairs of integers in list so that their sum is equal to integer x
def find_pairs(l, x):
    pairs = []
for (i, el_1) in enumerate(l):
    for (j, el_2) in enumerate(l[i+1:]):
        if el_1 + el_2 == x:
            pairs.append((el_1, el_2))
return pairs

NameError: name 'x' is not defined

In [95]:
#Compute the first n Fibonacci numbers
a, b = 0, 1
n = 10
for i in range(n):
    print(b)
a, b = b, a+b

1
1
1
1
1
1
1
1
1
1


In [96]:
#Check if a string is a palindrome
def is_palindrome(phrase):
    return phrase == phrase[::-1]
print(is_palindrome("anna")) # True

True


In [98]:
#Sort list with Quicksort algorithm
def qsort(L):
    if L == []: return []
return qsort([x for x in L[1:] if x< L[0]]) + L[0:1] +qsort([x for x in L[1:] if x>=L[0]])
lst = [44, 33, 22, 5, 77, 55, 999]
print(qsort(lst))

SyntaxError: 'return' outside function (Temp/ipykernel_13220/2602290117.py, line 4)

In [99]:
#Use list as stack, array,and queue
# as a list ...
l = [3, 4]
l += [5, 6] # l = [3, 4, 5, 6]
# ... as a stack ...
l.append(10) # l = [4, 5, 6, 10]
l.pop() # l = [4, 5, 6]
# ... and as a queue
l.insert(0, 5) # l = [5, 4, 5, 6]
l.pop() # l = [5, 4, 5]

6

In [102]:
#Find all permutations of string
def get_permutations(w):
    if len(w)<=1:
    return set(w)
smaller = get_permutations(w[1:])
perms = set()
for x in smaller:
for pos in range(0,len(x)+1):
     perm = x[:pos] + w[0] + x[pos:]
perms.add(perm)
return perms
print(get_permutations("nan"))

IndentationError: expected an indented block (Temp/ipykernel_13220/356644239.py, line 4)

Python Cheat Sheet: NumPy

The shape attribute of NumPy array a keeps a tuple of
integers. Each integer describes the number of elements of
the axis.

In [2]:
import numpy as np

In [3]:
#a.shape
a = np.array([[1,2],[1,1],[0,0]])
print(np.shape(a))

(3, 2)


The ndim attribute is equal to the length of the shape tuple

In [4]:
#a.ndim
print(np.ndim(a)) 

2


In [5]:
a = np.array([[2, 0], [0, 2]])
b = np.array([[1, 1], [1, 1]])
print(a*b) 

[[2 0]
 [0 2]]


The standard matrix multiplication operator. Equivalent to the
@ operator

In [6]:
#np.matmul(a,b), a@b
print(np.matmul(a,b))

[[2 2]
 [2 2]]


Creates a new 1D numpy array with evenly spaced values

In [7]:
#np.arange([start, ]stop,[step, ])
print(np.arange(0,10,2))

[0 2 4 6 8]


Creates a new 1D numpy array with evenly spread elements
within the given interval

In [8]:
#np.linspace(start, stop,num=50)
print(np.linspace(0,10,3))

[ 0.  5. 10.]


Averages over all the values in the numpy array 

In [9]:
#np.average(a) 
a = np.array([[2, 0], [0, 2]])
print(np.average(a))

1.0


Replace the <slice> as selected by the slicing operator with
the value <val>.


In [10]:
#<slice> = <val>
a = np.array([0, 1, 0, 0, 0])
a[::2] = 2
print(a) 

[2 1 2 0 2]


Calculates the variance of a numpy array

In [11]:
#np.var(a)
a = np.array([2, 6])
print(np.var(a))

4.0


Calculates the standard deviation of a numpy array

In [12]:
#np.std(a)
print(np.std(a))

2.0


Calculates the difference between subsequent values in
NumPy array a

In [13]:
#np.diff(a)
fibs = np.array([0, 1, 1, 2, 3, 5])
print(np.diff(fibs, n=1))

[1 0 1 1 2]


Calculates the cumulative sum of the elements in NumPy
array a.

In [14]:
#np.cumsum(a)
print(np.cumsum(np.arange(5)))

[ 0  1  3  6 10]


Creates a new NumPy array with the values from a
(ascending).

In [15]:
#np.sort(a)
a = np.array([10,3,7,1,0])
print(np.sort(a))

[ 0  1  3  7 10]


Returns the indices of a NumPy array so that the indexed
values would be sorted

In [16]:
#np.argsort(a)
a = np.array([10,3,7,1,0])
print(np.argsort(a))

[4 3 1 2 0]


Returns the maximal value of NumPy array a.

In [17]:
#np.max(a)
a = np.array([10,3,7,1,0])
print(np.max(a))

10


Returns the index of the element with maximal value in the
NumPy array a.

In [18]:
#np.argmax(a)
a = np.array([10,3,7,1,0])
print(np.argmax(a)) 

0


Returns the indices of the nonzero elements in NumPy array
a.

In [19]:
#np.nonzero(a)
a = np.array([10,3,7,1,0])
print(np.nonzero(a)) 

(array([0, 1, 2, 3], dtype=int64),)


Appends element x to the list lst

In [21]:
#list.append()
>>> l = []
>>> l.append(42)
>>> l.append(21)

Removes all elements from the list
lst–which becomes empty.

In [22]:
#list.clear()
>>> lst = [1, 2, 3, 4, 5]
>>> lst.clear()


Returns a copy of the list lst. Copies only
the list, not the elements in the list (shallow
copy).

In [23]:
#list.copy()
>>> lst = [1, 2, 3]
>>> lst.copy()

[1, 2, 3]

Counts the number of occurrences of
element x in the list lst.

In [24]:
#list.count()
>>> lst = [1, 2, 42, 2, 1, 42, 42]
>>> lst.count(42)
>>> lst.count(2)

2

Adds all elements of an iterable iter (e.g.
another list) to the list lst.

In [25]:
#list.extend()
>>> lst = [1, 2, 3]
>>> lst.extend([4, 5, 6])


Returns the position (index) of the first
occurrence of value x in the list lst.

In [26]:
#list.index()
>>> lst = ["Alice", 42, "Bob", 99]
>>> lst.index("Alice")
>>> lst.index(99, 1, 3)

ValueError: 99 is not in list

Inserts element x at position (index) i in
the list lst.


In [27]:
#list.insert()
>>> lst = [1, 2, 3, 4]
>>> lst.insert(3, 99)

Removes and returns the final element of
the list lst.

In [28]:
#list.pop()
>>> lst = [1, 2, 3]
>>> lst.pop()

3

Removes and returns the first occurrence
of element x in the list lst.

In [29]:
#list.remove()
>>> lst = [1, 2, 99, 4, 99]
>>> lst.remove(99)

Reverses the order of elements in the list
lst.


In [30]:
#list.reverse()
>>> lst = [1, 2, 3, 4]
>>> lst.reverse()

Sorts the elements in the list lst in
ascending order.


In [31]:
#list.sort()
>>> lst = [88, 12, 42, 11, 2]
>>> lst.sort()
# [2, 11, 12, 42, 88]
>>> lst.sort(key=lambda x: str(x)[0])